In [1]:
# Loading libraries
import numpy as np
import pandas as pd

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
print(string_data)

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object


In [3]:
string_data.isnull() # Check for sentinel value

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None
string_data.isnull() # again, check for sentinel value

0     True
1    False
2     True
3    False
dtype: bool

In [5]:
string_data.dropna()

1    artichoke
3      avocado
dtype: object

In [6]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [7]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
print(data, '\n')
print(cleaned)

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0 

     0    1    2
0  1.0  6.5  3.0


In [10]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [11]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [12]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
df = pd.DataFrame(np.random.randn(7, 3))
print(df)

          0         1         2
0 -0.931424  0.445261  0.689413
1  0.665435 -1.196695 -1.724078
2  0.029195 -1.176362  1.655855
3  0.389506  0.095660  0.985043
4  0.615768 -1.411578 -0.317185
5 -0.288349  2.224176  2.018170
6 -0.166206  1.364846  1.959249


In [14]:
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
print(df)

          0         1         2
0 -0.931424       NaN       NaN
1  0.665435       NaN       NaN
2  0.029195       NaN  1.655855
3  0.389506       NaN  0.985043
4  0.615768 -1.411578 -0.317185
5 -0.288349  2.224176  2.018170
6 -0.166206  1.364846  1.959249


In [15]:
df.dropna()

0         1         2
4  0.615768 -1.411578 -0.317185
5 -0.288349  2.224176  2.018170
6 -0.166206  1.364846  1.959249

In [16]:
df.dropna(thresh=2)

0         1         2
2  0.029195       NaN  1.655855
3  0.389506       NaN  0.985043
4  0.615768 -1.411578 -0.317185
5 -0.288349  2.224176  2.018170
6 -0.166206  1.364846  1.959249

In [17]:
df.fillna(0)

0         1         2
0 -0.931424  0.000000  0.000000
1  0.665435  0.000000  0.000000
2  0.029195  0.000000  1.655855
3  0.389506  0.000000  0.985043
4  0.615768 -1.411578 -0.317185
5 -0.288349  2.224176  2.018170
6 -0.166206  1.364846  1.959249

In [18]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.931424  0.500000  0.000000
1  0.665435  0.500000  0.000000
2  0.029195  0.500000  1.655855
3  0.389506  0.500000  0.985043
4  0.615768 -1.411578 -0.317185
5 -0.288349  2.224176  2.018170
6 -0.166206  1.364846  1.959249

In [19]:
df.fillna(0, inplace=True)

In [20]:
df

0         1         2
0 -0.931424  0.000000  0.000000
1  0.665435  0.000000  0.000000
2  0.029195  0.000000  1.655855
3  0.389506  0.000000  0.985043
4  0.615768 -1.411578 -0.317185
5 -0.288349  2.224176  2.018170
6 -0.166206  1.364846  1.959249

In [21]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  1.631981  1.031448 -0.206641
1 -0.433653  2.102438  1.339067
2  0.260378       NaN  0.908589
3  1.056487       NaN  0.096866
4  2.526341       NaN       NaN
5 -0.623645       NaN       NaN

In [22]:
df.fillna(method='ffill')

0         1         2
0  1.631981  1.031448 -0.206641
1 -0.433653  2.102438  1.339067
2  0.260378  2.102438  0.908589
3  1.056487  2.102438  0.096866
4  2.526341  2.102438  0.096866
5 -0.623645  2.102438  0.096866

In [23]:
df.fillna(method='ffill', limit=2)

0         1         2
0  1.631981  1.031448 -0.206641
1 -0.433653  2.102438  1.339067
2  0.260378  2.102438  0.908589
3  1.056487  2.102438  0.096866
4  2.526341       NaN  0.096866
5 -0.623645       NaN  0.096866

In [24]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[:2, 1] = NA
df.iloc[:4, 2] = NA
df

0         1         2
0  1.565544       NaN       NaN
1 -0.365113       NaN       NaN
2 -0.880208  0.777638       NaN
3 -0.087499  2.248699       NaN
4  0.267973  1.053783  0.841678
5 -0.516646  1.250886  0.701064

In [25]:
df.fillna(method='bfill')

0         1         2
0  1.565544  0.777638  0.841678
1 -0.365113  0.777638  0.841678
2 -0.880208  0.777638  0.841678
3 -0.087499  2.248699  0.841678
4  0.267973  1.053783  0.841678
5 -0.516646  1.250886  0.701064

In [26]:
data = pd.Series([1., NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [27]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [28]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [29]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [30]:
#data.drop_duplicates(inplace=True)

In [31]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [32]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [33]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [34]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [35]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [36]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
    }

In [37]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [38]:
data['animal'] = lowercased.map(meat_to_animal)

In [39]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [40]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [41]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [42]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [43]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [44]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [45]:
data.replace([-999, -1000], [np.nan, 0]) # List approach
data.replace({-999: np.nan, -1000: 0}) # Dict approach

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [46]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'], columns=['one', 'two', 'three', 'four'])

In [47]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [48]:
transform = lambda x: x[:4].upper()

<function __main__.<lambda>(x)>

In [49]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [50]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [51]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [52]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [53]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [69]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [70]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [71]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [72]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [73]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [74]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [75]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [76]:
data = np.random.rand(20)
data

array([0.315591  , 0.41885198, 0.26193734, 0.46886364, 0.54201392,
       0.40989999, 0.09245908, 0.18262837, 0.52036389, 0.85046288,
       0.6865272 , 0.18836703, 0.27152107, 0.4869974 , 0.08347632,
       0.85023918, 0.50285534, 0.21424011, 0.93537289, 0.97101754])

In [79]:
cats = pd.cut(data, 4, precision=2)
pd.value_counts(cats)

(0.31, 0.53]     7
(0.083, 0.31]    7
(0.75, 0.97]     4
(0.53, 0.75]     2
dtype: int64

In [80]:
data = np.random.randn(1000)
data

array([ 2.58874406e-01, -8.63625479e-01, -2.30276372e+00, -1.01117397e-01,
       -1.50602258e+00, -1.22642186e+00, -8.52037072e-01,  2.34790406e-01,
        7.56720993e-01, -2.76976056e-02,  1.65954757e+00, -1.46326742e+00,
        1.05173414e+00,  3.63280000e-01,  5.76397035e-01,  6.96360927e-01,
       -4.46895917e-01, -1.33723556e-01, -7.64251671e-01,  8.51233058e-01,
       -1.34403445e+00,  1.68693861e+00, -1.39186489e+00,  7.57793845e-02,
       -1.87419940e+00,  2.20773331e-01, -1.49567994e-01,  1.23378348e+00,
       -7.23745751e-01, -8.18006787e-02,  2.50921863e-01, -9.38332286e-01,
        9.46718932e-01,  2.54207063e-01, -9.76487557e-01,  9.54107750e-01,
       -2.21523356e+00, -6.65712837e-01,  5.72538153e-01, -7.01617190e-01,
        1.11642223e+00, -6.31121752e-01, -1.09205891e+00,  6.55962239e-01,
       -8.70818148e-02, -1.66423023e+00,  5.50698402e-02, -1.29364570e+00,
       -6.43769971e-01,  1.73741531e+00, -1.91573003e+00,  2.40327761e-01,
        1.31370615e+00, -

In [81]:
cats = pd.qcut(data, 4)
cats

[(0.0495, 0.752], (-3.53, -0.668], (-3.53, -0.668], (-0.668, 0.0495], (-3.53, -0.668], ..., (-0.668, 0.0495], (-0.668, 0.0495], (-3.53, -0.668], (-0.668, 0.0495], (0.0495, 0.752]]
Length: 1000
Categories (4, interval[float64]): [(-3.53, -0.668] < (-0.668, 0.0495] < (0.0495, 0.752] < (0.752, 3.181]]

In [82]:
pd.value_counts(cats)

(0.752, 3.181]      250
(0.0495, 0.752]     250
(-0.668, 0.0495]    250
(-3.53, -0.668]     250
dtype: int64

In [84]:
cats = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])
cats

[(0.0495, 1.291], (-1.31, 0.0495], (-3.53, -1.31], (-1.31, 0.0495], (-3.53, -1.31], ..., (-1.31, 0.0495], (-1.31, 0.0495], (-1.31, 0.0495], (-1.31, 0.0495], (0.0495, 1.291]]
Length: 1000
Categories (4, interval[float64]): [(-3.53, -1.31] < (-1.31, 0.0495] < (0.0495, 1.291] < (1.291, 3.181]]

In [85]:
pd.value_counts(cats)

(0.0495, 1.291]    400
(-1.31, 0.0495]    400
(1.291, 3.181]     100
(-3.53, -1.31]     100
dtype: int64

In [91]:
data = pd.DataFrame(np.random.randn(1000, 4))
data

0         1         2         3
0    0.486968 -1.083656  1.277137  0.122177
1    0.397829 -1.424641 -0.014910  0.273817
2    1.338118  0.080112 -0.493964 -0.295947
3   -1.055828  1.507248 -1.212898  0.938595
4   -1.172598 -1.483111 -0.266436  0.024433
..        ...       ...       ...       ...
995  0.837263 -1.363698  0.487379 -0.637349
996  1.518945  0.061126  0.506283 -1.564272
997 -0.903585 -0.179685 -1.712567  0.191812
998 -2.157396  1.031951 -0.768216  1.111862
999  0.059612  0.854164  0.579471  0.732392

[1000 rows x 4 columns]

In [92]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002728     0.009648    -0.039414    -0.017802
std       0.959128     1.002432     0.994127     1.034712
min      -2.763524    -2.821876    -3.161491    -3.441682
25%      -0.693488    -0.735367    -0.718105    -0.724959
50%       0.012093     0.035099    -0.018008    -0.023798
75%       0.664105     0.729981     0.633069     0.653642
max       2.722078     2.951629     2.993418     2.782595

In [93]:
col = data[2]

In [96]:
col[np.abs(col) > 3]

122   -3.161491
787   -3.112835
Name: 2, dtype: float64

In [97]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
122  0.019350 -0.501194 -3.161491 -1.898137
787  0.515586  1.713387 -3.112835  0.482029
845  0.827370  0.987402  1.376020 -3.441682

In [100]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002728     0.009648    -0.039140    -0.017360
std       0.959128     1.002432     0.993289     1.033342
min      -2.763524    -2.821876    -3.000000    -3.000000
25%      -0.693488    -0.735367    -0.718105    -0.724959
50%       0.012093     0.035099    -0.018008    -0.023798
75%       0.664105     0.729981     0.633069     0.653642
max       2.722078     2.951629     2.993418     2.782595

In [101]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1  1.0 -1.0 -1.0  1.0
2  1.0  1.0 -1.0 -1.0
3 -1.0  1.0 -1.0  1.0
4 -1.0 -1.0 -1.0  1.0

In [104]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [105]:
sampler = np.random.permutation(5)
sampler

array([4, 0, 3, 1, 2])

In [106]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11

In [107]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
0   0   1   2   3

In [108]:
choices = pd.Series([5, 7, -1, 6, 4])

In [112]:
draws = choices.sample(n=10, replace=True)
draws

3    6
0    5
0    5
2   -1
2   -1
2   -1
2   -1
1    7
2   -1
4    4
dtype: int64

In [114]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [115]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [117]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [119]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [123]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [124]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [127]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [128]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [129]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [130]:
'::'.join(pieces)

'a::b::guido'

In [131]:
'guido' in val

True

In [132]:
val.index(',')

1

In [133]:
val.find(':')

-1

In [134]:
val.index(':')

ValueError: substring not found

In [135]:
val.count(',')

2

In [136]:
val.replace(',', '::')

'a::b:: guido'

In [137]:
val.replace(',', '')

'ab guido'

In [139]:
import re

text = "foo bar\t baz \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [140]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [141]:
regex.findall(text)

[' ', '\t ', ' \t']

In [142]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

regex = re.compile(pattern, flags=re.IGNORECASE)

In [143]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [144]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [145]:
text[m.start():m.end()]

'dave@google.com'

In [146]:
print(regex.match(text))

None


In [147]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [149]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [150]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [151]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

